version: "3.9"

networks:
  mynet:
    name: mynet

services:
  # server:
  #   build:
  #     context: ./
  #     dockerfile: ./server/Dockerfile
  #   container_name: server
  #   networks: 
  #     mynet:
  #       aliases:  
  #         - server_1

  loadbalancer: 
    build: 
      context: ./
      dockerfile: ./loadbalancer/Dockerfile
    image: loadbalancerim
    container_name: loadbalancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
    privileged: true
    networks:
      mynet:
        aliases:  
          - loadbalancer

  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    image: clientim
    container_name: client
    ports: 
      - "8081:8081"
    networks:
      mynet:
        aliases:
          - client